sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  - DOCKER_USERNAME='prh83+prh83'
  - DOCKER_PASSWORD='5HNY9Q13Y4OMNUR7C5TPFASKI9ZGXO0TPGI6MYFVZ9BGZV4OV8PQFJFDPC5FFBD6'

branches:
  only:
  - all-services-developed

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - npm install --only=production

install: 
  - yarn install

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 10

script:
  - make brand
  - make package
  - make qa

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker
    - env: SERVICE=recipes-id-generator
      services:
        - docker

